/**
 * Turn a missing icon into a sentence rather than a cargo backtrace.
 *
 * `tauri build` on Windows needs `src-tauri/icons/icon.ico` and fails for it three hundred
 * lines into a Rust compile, inside a build script, which reads as "the checkout is broken".
 *
 * This used to guard a deliberate gap — the repository shipped no icon at all, because Incudo
 * never generates artwork and none had been drawn yet. The icons are here now, generated from
 * the real logo in `brand/`, so the check is no longer about a missing commitment. It stays
 * because the failure it explains is still just as unreadable, and because the icons are
 * regenerated by a command that can be run wrong.
 */

import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const icons = join(here, '..', 'src-tauri', 'icons');

// Everything `tauri.conf.json` lists under `bundle.icon`. Checking only `icon.ico` would let a
// half-generated set through and fail later, on a different platform, for a different reason.
const required = ['icon.ico', 'icon.icns', '32x32.png', '128x128.png', '128x128@2x.png'];
const missing = required.filter((name) => !existsSync(join(icons, name)));

if (missing.length > 0) {
  process.stderr.write(
    [
      '',
      `The Tauri bundle is missing ${missing.length} icon file(s):`,
      '',
      ...missing.map((name) => `  ${join(icons, name)}`),
      '',
      'Regenerate the whole set from the logo:',
      '',
      '  cd apps/desktop',
      '  npx tauri icon ../../brand/incudo-logo-white-1080.png',
      '',
      'See apps/desktop/src-tauri/icons/README.md — including which files that command',
      'writes that this repository deliberately does not keep.',
      '',
      'Meanwhile the whole application runs in a browser with no Rust and no icon:',
      '',
      '  npm run desktop',
      '',
    ].join('\n'),
  );
  process.exit(1);
}
