[package]
name = "incudo-desktop"
version = "0.0.1"
description = "Incudo desktop shell"
edition = "2021"
rust-version = "1.77"
publish = false

[lib]
name = "incudo_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-http = "2"

[profile.release]
codegen-units = 1
lto = true
strip = true
